version: "1"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    image: mongo:latest
    ports:
      - "8081:27017"
  app:
    image: myapp:latest
    ports:
      - "8082:3000"
